// <auto-generated />
#nullable enable

namespace DreamBig.Repository.Cosmos.Attributes;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("DreamBig.Repository.Cosmos", "1.0.0")]
[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class UseRepoAttribute : global::System.Attribute
{
}