//HintName: UserRepository.g.cs
// <auto-generated />
#nullable enable

using DreamBig.Repository.Abstractions;
using DreamBig.Repository.Cosmos;
using Microsoft.Extensions.Logging;

namespace SomeNamespace.Models;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("DreamBig.Repository.Cosmos", "1.0.0")]
public partial class UserRepository<T> : BaseRepository<T> where T : IEntity
{
    public UserRepository(BaseProvider? cosmosProvider, string? containerName = null, ILogger<UserRepository<T>>? logger = null) : base(cosmosProvider, containerName, logger)
    {
    }
}