// <auto-generated />
#nullable enable

using DreamBig.Repository.Abstractions;
using DreamBig.Repository.Cosmos;
using Microsoft.Azure.Cosmos;
using Microsoft.Extensions.Logging;

namespace _TheNamespace_;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("DreamBig.Repository.Cosmos", "1.0.0")]
public partial class _TheEntity_Repository : BaseRepository<_TheEntity_>
{
    public _TheEntity_Repository(IProvider<CosmosClient, Database>? cosmosProvider, string? containerName = null, ILogger<_TheEntity_Repository>? logger = null) : base(cosmosProvider, containerName, logger)
    {
    }
}