// <auto-generated />
#nullable enable

namespace DreamBig.Repository.Generators.Attributes;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("DreamBig.Repository.Generators", "1.0.0")]
[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class UseFastRepoAttribute : global::System.Attribute
{
}